spring:
  application:
    name: magic-bag-common
  # 默认的redis配置，引用common工具模块的模块需要覆盖redis配置
  data:
    redis:
      host: localhost
      port: 6379

common:
  url: http://localhost:10016
  jwt:
    secret: k3b8Xq1v2Zm9Yp6Wn5Lr8As3Dx7Cv1Bn9Mq4Xs8Vj2Kp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4A==
    expire-minutes: 120
    renew-threshold-minutes: 30
  rsa:
    boot: true
    public-key-path: .keys/public-key.pem
    private-key-path: .keys/private-key.pem
