spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 54.169.196.90:8848  # Nacos服务注册地址
        group: MAGIC_BAG
      config:
        server-addr: 54.169.196.90:8848  # Nacos配置中心地址

  kafka:
    bootstrap-servers: 54.169.196.90:9092
    consumer:
      group-id: magic-bag
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: nus.iss.se.kafka.event

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false