server:
  port: 10021

spring:
  profiles:
    active: dev
  application:
    name: magic-bag-payment
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=${spring.application.name}&refresh=true
      - nacos:shared-config.yaml?refresh=true
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 3.1.213.148:8848
        group: MAGIC_BAG
      config:
        server-addr: 3.1.213.148:8848

stripe:
  api:
    key: sk_test_51QkKIAFx9r3W1cEdHhvIXcgV4oTkl7vLuFDttGigZxNaTiiw4VR7nWFCQxssdTnzjgX2376tBdYNx9UniYJ00GwesjEGB
app:
  pay-url: http://localhost:10021
